baseurl = "http://dev2820.github.io/"
title = "dev2820 개발일지"

languageCode = "ko-KR"
DefaultContentLanguage = "kr"
theme = "hugo-amania"
disqusShortname = "XXXX"
googleAnalytics = "UA-XXXXXXXX-X"
paginate = 7
paginatePath = "page"

[author]
    name = "dev2820"
    email = "second28200@naver.com"

[params]
    description = "dev2820의 개발일지 저장소"
