baseurl = "http://dev2820.github.io/"
title = "dev2820 개발일지"

languageCode = "ko-KR"
DefaultContentLanguage = "kr"
theme = "hugo-mania"
disqusShortname = "dev2820-github-io"
googleAnalytics = "UA-XXXXXXXX-X"
paginate = 7
paginatePath = "page"
summaryLength = 70
hasCJKLanguage = true
pygmentsCodefences = true
pygmentsStyle = "dracula"
pygmentsOptions = "linenos=table,anchorlinenos=true,lineanchors=prefix"
sectionPagesMenu = "main"
enableRobotsTXT = true

[outputs]
    home = ["HTML", "RSS", "JSON"]

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"

[author]
    name = "dev2820"
    email = "second28200@gmail.com"
    cover = "/images/ocean.jpg"
    introduce = "풀스텍 웹개발을 지향합니다"
 
[params]
    description = "dev2820의 개발일지 저장소"
    notFound = "/images/404NotFound.png"
    logo = "/images/logo.png"
    siteLogo = "/images/site_logo_dark.png"
    bannerBottom = "/images/banner_bottom.png"
    defaultSummaryImage = "/images/default_summary.png"
    asideBackgroundImage = "/images/space.jpg"

[taxonomies]
    category = "categories"
    tag = "tags"
    subcategory = "subcategories"