baseurl = "http://dev2820.github.io/"
title = "dev2820 개발일지"

languageCode = "ko-KR"
DefaultContentLanguage = "kr"
theme = "hugo-amania"
disqusShortname = "XXXX"
googleAnalytics = "UA-XXXXXXXX-X"
paginate = 7
paginatePath = "page"
summaryLength = 70
hasCJKLanguage = true
pygmentsCodefences = true
pygmentsStyle = "dracula"

[author]
    name = "dev2820"
    email = "second28200@naver.com"
    cover = "/images/ocean.jpg"
    introduce = "풀스텍 웹개발을 지향합니다"

[params]
    description = "dev2820의 개발일지 저장소"
    cover = "/images/space.jpg"
    notFound = "/images/not_found.png"
    logo = "/images/logo.png"